# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

gems:
  - jekyll-sitemap

# Site settings
title: VitaEmu
email: noemailfornow
description: > # this means to ignore newlines until "baseurl:"
  VitaEmu.com goal is to put all interesting links about PS Vita emulation and homebrew scene in one place.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://vitaemu.com" # the base hostname & protocol for your site
twitter_username: lologh
github_username:  lologhi

# Build settings
markdown: kramdown
